version: '3.4'

services:
  app1:
    image: app1:latest
    container_name: app1
    build: .
    environment:
      PORT: 3000
      HOST: http://localhost:3000
      APP_HOST: http://localhost:3000
      NODE_ENV: production
      MONGOHQ_URL: mongodb+srv://quochuydev:Quochuydev548!@cluster0.stlus.mongodb.net/qhdapp?retryWrites=true&w=majority
    ports:
      - 3000:3000
