const mongoose = require('mongoose');
const { Schema } = mongoose;

const WooOrderSchema = new Schema({
  id: { type: Number, default: null },
  parent_id: { type: Number, default: null },
  number: { type: String, default: null },
  order_key: { type: String, default: null }, //wc_order_glrerNIiDxU5T
  created_via: { type: String, default: null },
  version: { type: String, default: null },
  status: { type: String, default: null },
  currency: { type: String, default: null },
  date_created: { type: Date, default: null },
  date_created_gmt: { type: Date, default: null },
  date_modified: { type: Date, default: null },
  date_modified_gmt: { type: Date, default: null },
  discount_total: { type: Number, default: null },
  discount_tax: { type: Number, default: null },
  shipping_total: { type: Number, default: null },
  shipping_tax: { type: Number, default: null },
  cart_tax: { type: Number, default: null },
  total: { type: Number, default: null },
  total_tax: { type: Number, default: null },
  prices_include_tax: { type: Boolean, default: false },
  customer_id: { type: Number, default: null },
  customer_ip_address: { type: String, default: null },
  customer_user_agent: { type: String, default: null },
  customer_note: { type: String, default: null },
  billing: {
    first_name: { type: String, default: null },
    last_name: { type: String, default: null },
    company: { type: String, default: null },
    address_1: { type: String, default: null },
    address_2: { type: String, default: null },
    city: { type: String, default: null },
    state: { type: String, default: null },
    postcode: { type: String, default: null },
    country: { type: String, default: null },
    email: { type: String, default: null },
    phone: { type: String, default: null },
  },
  shipping: {
    first_name: { type: String, default: null },
    last_name: { type: String, default: null },
    company: { type: String, default: null },
    address_1: { type: String, default: null },
    address_2: { type: String, default: null },
    city: { type: String, default: null },
    state: { type: String, default: null },
    postcode: { type: String, default: null },
    country: { type: String, default: null },
    email: { type: String, default: null },
    phone: { type: String, default: null },
  },
  payment_method: { type: String, default: null },
  payment_method_title: { type: String, default: null },
  transaction_id: { type: String, default: null },
  date_paid: { type: Date, default: null },
  date_paid_gmt: { type: Date, default: null },
  date_completed: { type: Date, default: null },
  date_completed_gmt: { type: Date, default: null },
  cart_hash: { type: String, default: null },
  meta_data: [],
  line_items: [{
    id: { type: Number, default: null },
    name: { type: String, default: null },
    product_id: { type: Number, default: null },
    variation_id: { type: Number, default: null },
    quantity: { type: Number, default: null },
    tax_class: { type: String, default: null },
    subtotal: { type: Number, default: null },
    subtotal_tax: { type: Number, default: null },
    taxes: [],
    meta_data: [],
    sku: { type: String, default: null },
    price: { type: Number, default: null },
  }],
  tax_lines: [],
  shipping_lines: [],
  fee_lines: [],
  coupon_lines: [],
  refunds: [],
  _links: {}
})

mongoose.model('WooOrder', WooOrderSchema);